feat: add csai demo
DiceTechnology/doris-android-example pull request #11
Opened 2024-01-24 09:06 UTC by hongfeih-es

add csai demo and doc

2024-01-24 09:24 UTC, guoen21 approved these changes, later dismissed

2024-01-24 09:24 UTC, guoen21 commented on build.gradle
> +    id 'org.jetbrains.kotlin.android' version '1.9.22' apply false
our doris-android use 1.8 and mobile app use 1.7, not sure we should use 1.9 or lower on example app.

2024-01-24 09:24 UTC, guoen21 commented on video/build.gradle
> +        exclude group: 'com.github.DiceTechnology', module: 'dice-shield-android'
we can remove this line

2024-01-24 09:24 UTC, guoen21 commented on video/build.gradle
> +        exclude group: 'com.github.DiceTechnology', module: 'dice-shield-android'
we can remove this line

2024-01-24 10:01 UTC, szaboa approved these changes, later dismissed

2024-01-24 10:08 UTC, guoen21 submitted a review, later dismissed

2024-01-26 05:01 UTC, guoen21 requested changes

2024-01-26 05:01 UTC, guoen21 commented on csai/src/main/java/com/dice/doris/csai/MainActivity.kt
> +                setAdViewProvider(playerView)
For ima csai live player, we need two players, one for content playback, second for ad player.

2024-01-30 07:32 UTC, guoen21 commented on csai/src/main/java/com/dice/doris/csai/MainActivity.kt
> +                setAdViewProvider(playerView)
try to fix it with #13

2024-01-30 09:04 UTC, guoen21 approved these changes, later dismissed

2024-01-31 01:30 UTC, guoen21 reviewed
Need to fix the NPE crash issue.
![Screen Shot 2024-01-30 at 11 08 31](https://github.com/DiceTechnology/doris-android-example/assets/83813094/ec794f85-e330-4cf7-b3ef-39b7b8f433d3)

2024-02-01 07:53 UTC, guoen21 approved these changes

2024-02-01 07:54 UTC, WeiLiuSH approved these changes

2024-02-01 10:22 UTC, merged